MIN_WIDTH = 17
MIN_HEIGHT = 17
X_SCALE = 4
Y_SCALE = 2
MAX_BRICKS = 15
BMAN = [['[', '^', '^', ']'], [' ', ']', '[', ' ']]
MAX_ENEMY = 5
ENEM = [['(', '@', '@', ')'], [' ', ')', '(', ' ']]
BM = '@'
EM = '!'
BR = '%'
WL = '#'
